### ISSUE TITLE
Android P适配还是有点问题

### ISSUE THREAD

**Issue by nadazero** [ShamsChu/MenuPopupView#3]
![1](https://user-images.githubusercontent.com/10139727/46590636-58bf7a80-cae7-11e8-9aac-49fafb1eba07.jpg)
![2](https://user-images.githubusercontent.com/10139727/46590637-59581100-cae7-11e8-8b7f-afe99d788a29.jpg)

如图，在android 8之前还是一切正常的，但在android P(android 9)上间隔的白线明显就有问题了。

**Comment by Ryan-Shz** [comment]
fixed
